In [ ]:
import numpy as np

In [ ]:
vector = np.arange(50000000)

In [ ]:
print(vector)

[       0        1        2 ... 49999997 49999998 49999999]


In [ ]:
np.arange(24).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
import pandas as pd
tips = pd.read_csv('tips.csv')

In [ ]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [ ]:
tips.values # .values will convert a dataframe into a numpy array

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
mat1 = np.random.randint(10, 51, size = (3,3))
mat2 = np.random.randint(50, 100, size = (3,3))

In [ ]:
mat1

array([[23, 20, 39],
       [42, 42, 41],
       [16, 34, 37]])

In [ ]:
mat2

array([[64, 67, 50],
       [84, 57, 91],
       [84, 56, 65]])

In [ ]:
#addition of matrices
mat1 + mat2 #np.add(mat1, mat2)

array([[ 87,  87,  89],
       [126,  99, 132],
       [100,  90, 102]])

In [ ]:
mat1 + 10

array([[33, 30, 49],
       [52, 52, 51],
       [26, 44, 47]])

In [ ]:
#subtraction of matrices
mat1 - mat2   #np.subtract(mat1, mat2)

array([[-41, -47, -11],
       [-42, -15, -50],
       [-68, -22, -28]])

In [ ]:
mat2 - mat1

array([[41, 47, 11],
       [42, 15, 50],
       [68, 22, 28]])

In [ ]:
#division of matrices
mat1 / 10

array([[3.9, 2.3, 1. ],
       [1.8, 4.9, 2.9],
       [2.7, 1.1, 3.5]])

In [ ]:
mat1 / mat2  #np.divide(mat1, mat2)

array([[0.36842105, 0.53333333, 0.34545455],
       [0.60810811, 0.14457831, 0.171875  ],
       [0.44444444, 0.4556962 , 0.390625  ]])

In [ ]:
#element-wise multiplication or Hadamard product
mat1 * mat2   #np.multiply(mat1, mat2)

array([[1472, 1340, 1950],
       [3528, 2394, 3731],
       [1344, 1904, 2405]])

In [ ]:
#actual matrix multiplication : Dot product
mat1 @ mat2 #np.dot(mat1, mat2)

array([[6428, 4865, 5505],
       [9660, 7504, 8587],
       [6988, 5082, 6299]])

In [ ]:
mat1

array([[28, 40, 19],
       [45, 12, 11],
       [28, 36, 25]])

In [ ]:
#transpose of a matrix
mat1.T

array([[23, 42, 16],
       [20, 42, 34],
       [39, 41, 37]])

In [ ]:
#matrix rank : helps us to identify duplicate or redundant data
np.linalg.matrix_rank(mat1)

np.int64(3)

In [ ]:
#determinant of a matrix : whether a matrix is singular or not
np.linalg.det(mat1)

np.float64(15204.000000000015)

In [ ]:
mat3 = np.arange(9).reshape(3,3)

In [ ]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.det(mat3)

np.float64(0.0)

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
#inverse of a matrix
mat1_inv = np.linalg.inv(mat1)

In [ ]:
mat1_inv

array([[ 0.01052355,  0.03854249, -0.05380163],
       [-0.0590634 ,  0.01493028,  0.04571165],
       [ 0.04972376, -0.03038674,  0.00828729]])

In [ ]:
np.round((mat1_inv @ mat1), 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
matrix = np.array([[3, -2],
                   [1, 0]])

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Original Matrix: ")
print(matrix)
print('\nEigenvalues: ')
print(eigenvalues)
print('\nEigenvectors: ')
print(eigenvectors)

Original Matrix: 
[[ 3 -2]
 [ 1  0]]

Eigenvalues: 
[2. 1.]

Eigenvectors: 
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
np.dot(matrix, [0.89442719, 0.4472136])

array([1.78885437, 0.89442719])

In [ ]:
np.array([0.89442719, 0.4472136]) * 2

array([1.78885438, 0.8944272 ])