<a href="https://colab.research.google.com/github/Rishabh-0408/Data-Science-and-AI/blob/main/Numpy/Numpy_Handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Create two numpy arrays with data types integer and float
# [1,2,3,4,5,6]

In [4]:
arr1 = np.array([1,2,3,4,5],dtype=float)
arr1

array([1., 2., 3., 4., 5.])

In [6]:
arr2 = np.array([1,2,3,4,5],dtype=int)
arr2

array([1, 2, 3, 4, 5])

In [ ]:
# Create numpy arrays with zero , one , two , three dimensions respectively
# Print the shape and dimensions of each

In [8]:
a0 = np.array(10)
print(a0)
print(a0.shape)
print(a0.ndim)

10
()
0


In [10]:
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [11]:
print(a1.shape)
print(a1.ndim)

(3,)
1


In [12]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print(a2)
print(a2.shape)
print(a2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [13]:
a3 = np.array([[[1, 2],
                [3, 4]],

               [[5, 6],
                [7, 8]]])
print(a3)
print(a3.shape)
print(a3.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
# Create 2*2 , 3*3 , 4*4 , 5*9 identity matrix

In [14]:
i_arr = np.identity(2,dtype = int)
print(i_arr)

[[1 0]
 [0 1]]


In [15]:
i_arr = np.identity(3,dtype = int)
print(i_arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
i_arr = np.identity(4,dtype = int)
print(i_arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
eye_arr = np.eye(5,9,dtype = int)
print(eye_arr)

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


In [ ]:
# Create a 1D , 2D , 3D array using arange and reshape methods

In [29]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
arr_2d = np.arange(10).reshape(2, 5)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [37]:
arr_3d = np.arange(4).reshape(1,2,2) #how to identify to separate just multiply and if we get the last value like range from (0,18) 2x3x3 is then valid
print(arr_3d)

[[[0 1]
  [2 3]]]


In [39]:
arr_3d.shape

(1, 2, 2)

In [40]:
arr_3d.ndim

3

In [ ]:
# Create an array with shape 3*5 , with all the elements as 200

In [41]:
arr_full = np.full((3,3),200)
print(arr_full)

[[200 200 200]
 [200 200 200]
 [200 200 200]]


In [ ]:
# Try to acheive this result thorugh a diff way
# Atleast 2 methods

In [44]:
arr1 = np.ones((3,3),dtype=int)*200
print(arr1)

[[200 200 200]
 [200 200 200]
 [200 200 200]]


In [49]:
arr0 = np.zeros((3,3),dtype=int)+200
print(arr0)
print(type(arr0))

[[200 200 200]
 [200 200 200]
 [200 200 200]]
<class 'numpy.ndarray'>


In [ ]:
# Create a numpy array with random integers in the range of 0 to 150
# The sample size = 20
# After this , give me all the unique values in the array
# Also try fixing the values

In [50]:
np.random.seed(0)
arr_random = np.random.randint(0,151,size = 20)
print(arr_random)

[ 47 117  67 103   9  21  36  87  70  88 140  58  39  87  88  81  25  77
  72   9]


In [51]:
print(np.unique(arr_random))

[  9  21  25  36  39  47  58  67  70  72  77  81  87  88 103 117 140]


In [53]:
# Create a numpy array with shape 2*3 , with random integers from 0 to 100
# Reshape the array into shape 3*2

In [54]:
arr = np.random.randint(0,100, size = (2,3))
print(arr)

[[20 80 69]
 [79 47 64]]


In [57]:
arr = arr.reshape(3,2)
print(arr)

[[20 80]
 [69 79]
 [47 64]]


In [ ]:
# Create a numpy array with values from 1 to 6
# Replace all the odd numbers with -1
# Then reshape the array into 2 rows

In [62]:
arr = np.arange(1,7)
print(arr)
# for i in range(len(arr)):
#   if(arr[i] % 2 == 1):
#     arr[i] = -1
arr[arr% 2 != 0] = -1
arr = arr.reshape(2,3)
print(arr)

[1 2 3 4 5 6]
[[-1  2 -1]
 [ 4 -1  6]]


In [ ]:
# Take 5 random integers from 0 to 100 in an array
# Find the mean of the array
# Replace values below mean with 0
# Count how many values were replaced

In [73]:
np.random.seed(0)
arr = np.random.randint(0,101,size=10)
print(arr)
mean = np.mean(arr)
print(mean)
count = np.sum(arr < mean)
print(count)
arr[arr < mean] = 0
print(arr)

[44 47 64 67 67  9 83 21 36 87]
52.5
5
[ 0  0 64 67 67  0 83  0  0 87]


In [ ]:
# Practise Questions
# Create a 2D array with 2 rows , 3 columns
# Extract the top 2 values from each row

In [74]:
np.random.seed(0)
arr2d = np.random.randint(1,100, size = (2,3))
print(arr2d)

[[45 48 65]
 [68 68 10]]


In [79]:
sorted_Arr = np.sort(arr2d)
print(sorted_Arr)

[[45 48 65]
 [10 68 68]]


In [88]:
top2 = sorted_Arr[:,-2:]
print(top2)

[[48 65]
 [68 68]]
