<a href="https://colab.research.google.com/github/Rishabh-0408/Data-Science-and-AI/blob/main/Numpy/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#creating a array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr2 = np.array([1,2,3.4,True,4,"asb"])
arr2

array(['1', '2', '3.4', 'True', '4', 'asb'], dtype='<U32')

In [8]:
# Dimesions - it is represented by []
# 0 dimension array
arr3 = np.array(20)
arr3

array(20)

In [9]:
#ndim -> tell the number of dimensions
arr3.ndim

0

In [10]:
# 2 Dimension array
arr4 = np.array([[1,2],[3,4]])
arr4

array([[1, 2],
       [3, 4]])

In [12]:
arr4.ndim

2

In [14]:
#  Creating 3d array
three_arr = np.array([[[1,2,3],[4,5,6],[12,11,23]],[[7,8,9],[10,11,12],[34,23,345]]])
three_arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 12,  11,  23]],

       [[  7,   8,   9],
        [ 10,  11,  12],
        [ 34,  23, 345]]])

In [15]:
# Indexing
# for 1d array
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [16]:
print(arr[3])

40


In [17]:
# for 2d array
arr2 = np.array([[1,2,4,5],[3,6,8,7]])
arr2

array([[1, 2, 4, 5],
       [3, 6, 8, 7]])

In [18]:
arr2[0,2]

np.int64(4)

In [19]:
# Sclicing
# for 1d array
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [24]:
arr[2:5]

array([30, 40, 50])

In [25]:
# for 2d array
arr2 = np.array([[1,2,4,5],[3,6,8,7]])
arr2.shape

(2, 4)

In [30]:
arr2[1, 1:4]

array([6, 8, 7])

In [31]:
arr2[0:2, 1:3]

array([[2, 4],
       [6, 8]])

In [32]:
# for 3d array
three_arr = np.array([[[1,2,3],[4,5,6],[12,11,23]],[[7,8,9],[10,11,12],[34,23,345]]])
three_arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 12,  11,  23]],

       [[  7,   8,   9],
        [ 10,  11,  12],
        [ 34,  23, 345]]])

In [42]:
three_arr[0:3,0:3,1:3]

array([[[  2,   3],
        [  5,   6],
        [ 11,  23]],

       [[  8,   9],
        [ 11,  12],
        [ 23, 345]]])

In [44]:
# Reshape
# No of elements before reshaping = No of elements after reshaping
arr2 = np.array([[1,2,4,5],[3,6,8,7]])
arr2.shape

(2, 4)

In [46]:
arr2.reshape(1,8)

array([[1, 2, 4, 5, 3, 6, 8, 7]])

In [47]:
arr2.reshape(2,2,2)

array([[[1, 2],
        [4, 5]],

       [[3, 6],
        [8, 7]]])

In [48]:
arr2.reshape(1,4,2)

array([[[1, 2],
        [4, 5],
        [3, 6],
        [8, 7]]])