<a href="https://colab.research.google.com/github/Rishabh-0408/Data-Science-and-AI/blob/main/Numpy/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
#creating a array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr2 = np.array([1,2,3.4,True,4,"asb"])
arr2

array(['1', '2', '3.4', 'True', '4', 'asb'], dtype='<U32')

In [ ]:
# Dimesions - it is represented by []
# 0 dimension array
arr3 = np.array(20)
arr3

array(20)

In [ ]:
#ndim -> tell the number of dimensions
arr3.ndim

0

In [ ]:
# 2 Dimension array
arr4 = np.array([[1,2],[3,4]])
arr4

array([[1, 2],
       [3, 4]])

In [ ]:
arr4.ndim

2

In [ ]:
#  Creating 3d array
three_arr = np.array([[[1,2,3],[4,5,6],[12,11,23]],[[7,8,9],[10,11,12],[34,23,345]]])
three_arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 12,  11,  23]],

       [[  7,   8,   9],
        [ 10,  11,  12],
        [ 34,  23, 345]]])

In [ ]:
# Indexing
# for 1d array
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
print(arr[3])

40


In [ ]:
# for 2d array
arr2 = np.array([[1,2,4,5],[3,6,8,7]])
arr2

array([[1, 2, 4, 5],
       [3, 6, 8, 7]])

In [ ]:
arr2[0,2]

np.int64(4)

In [ ]:
# Sclicing
# for 1d array
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr[2:5]

array([30, 40, 50])

In [ ]:
# for 2d array
arr2 = np.array([[1,2,4,5],[3,6,8,7]])
arr2.shape

(2, 4)

In [ ]:
arr2[1, 1:4]

array([6, 8, 7])

In [ ]:
arr2[0:2, 1:3]

array([[2, 4],
       [6, 8]])

In [ ]:
# for 3d array
three_arr = np.array([[[1,2,3],[4,5,6],[12,11,23]],[[7,8,9],[10,11,12],[34,23,345]]])
three_arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [ 12,  11,  23]],

       [[  7,   8,   9],
        [ 10,  11,  12],
        [ 34,  23, 345]]])

In [ ]:
three_arr[0:3,0:3,1:3]

array([[[  2,   3],
        [  5,   6],
        [ 11,  23]],

       [[  8,   9],
        [ 11,  12],
        [ 23, 345]]])

In [ ]:
# Reshape
# No of elements before reshaping = No of elements after reshaping
arr2 = np.array([[1,2,4,5],[3,6,8,7]])
arr2.shape

(2, 4)

In [ ]:
arr2.reshape(1,8)

array([[1, 2, 4, 5, 3, 6, 8, 7]])

In [ ]:
arr2.reshape(2,2,2)

array([[[1, 2],
        [4, 5]],

       [[3, 6],
        [8, 7]]])

In [ ]:
arr2.reshape(1,4,2)

array([[[1, 2],
        [4, 5],
        [3, 6],
        [8, 7]]])

In [ ]:
# Random func
# Used to generate random values in ur numpy array

In [ ]:
x = np.random.randint(1,101)
x

In [ ]:
arr = np.random.randint(1,101, size = (4,4))
arr

In [ ]:
ludo = np.random.randint(1,7)
print(ludo)

5


In [ ]:
ludo = np.random.choice(7,1)
print(ludo)

[3]


In [3]:
np.random.seed(10) # generate once and then fix it
ar = np.random.randint(1,51, size = 25)
ar

array([10, 37, 16,  1, 50, 29, 26, 30, 49, 30, 50,  9, 10,  1, 43, 41, 37,
       17, 37, 48, 12, 25, 44, 34,  9])

In [4]:
# random

a = np.random.random((2,3)) # here random values are in the range 0 to 1 only
a

array([[0.87761494, 0.72743551, 0.54088093],
       [0.13145815, 0.41366737, 0.77872881]])

In [ ]:
# Methods

# np.zeros
# np.ones
# np.full
# np.identity
# np.eye

In [5]:
z_arr = np.zeros((3,3), dtype = "int")
z_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# np.ones

o_arr = np.ones((5,2), dtype = "int")
o_arr

In [ ]:
# np.full

full_arr = np.full((2,4), 5005)
full_arr

In [ ]:
full_arr.shape

In [ ]:
# np.identity()

ide_arr = np.identity(9, dtype = "int")
ide_arr

In [ ]:
# np.eye

# You can have equal as well as unequal number of rows and columns with 1 on the main diagonal and all other values are zero

e_arr = np.eye(3, dtype = "int")
e_arr

In [ ]:
e_arrr = np.eye(4,9)
e_arrr

In [6]:
# arange

x = np.arange(0,20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
x = np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# linspace
# eqaully separated values
x = np.linspace(0,10,num = 5)
x

In [ ]:
l = [1,2,3,4]
l1 = [3,4,5,6]

l+l1

In [ ]:
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
result = a+b
result